backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "partials"
    label: "Partials (Nav & Footer)"
    label_singular: "Partial"
    folder: "partials"
    extension: "html"
    create: true
    editor: { preview: false }
    fields:
      - { label: "File body (HTML)", name: "body", widget: "code", hint: "This edits the entire file." }

  - name: "pages"
    label: "Pages (Direct Edit)"
    editor: { preview: false }
    format: "raw"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Page HTML", name: "body", widget: "code" }
      - label: "Services Page"
        name: "services"
        file: "services.html"
        fields:
          - { label: "Page HTML", name: "body", widget: "code" }

  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "html"
    editor: { preview: false }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body (HTML/Markdown)", name: "body", widget: "markdown" }
    format: "frontmatter"
