backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:

  # ------- Global partials (edit site-wide HTML) -------
  - name: "partials"
    label: "Partials (Nav & Footer)"
    editor: { preview: false }
    files:
      - label: "Header (Navigation)"
        name: "header"
        file: "partials/header.html"
        fields:
          - { label: "Header HTML", name: "body", widget: "text", hint: "Edits the entire file." }
      - label: "Footer"
        name: "footer"
        file: "partials/footer.html"
        fields:
          - { label: "Footer HTML", name: "body", widget: "text", hint: "Edits the entire file." }

  # ------- Raw HTML pages (edit full page source) -------
  - name: "pages_raw"
    label: "Pages (Raw HTML)"
    editor: { preview: false }
    files:
      - label: "Home Page (Raw)"
        name: "home_raw"
        file: "index.html"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
      - label: "Services Page (Raw)"
        name: "services_raw"
        file: "services.html"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
      - label: "Meet Mike (Raw)"
        name: "meetmike_raw"
        file: "meetmike/index.html"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
      - label: "Testimonials (Raw)"
        name: "testimonials_raw"
        file: "testimonials/index.html"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
      - label: "Contact (Raw)"
        name: "contact_raw"
        file: "contact/index.html"
        fields:
          - { label: "HTML", name: "body", widget: "text" }

  # ------- Blog stays structured (markdown) -------
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "html"
    editor: { preview: false }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body (Markdown)", name: "body", widget: "markdown" }
    format: "frontmatter"
